# dist: xenial (the default) or newer required
language: node_js # Node 10 LTS or later required
node_js:
  - node
addons:
  chrome: stable # make Chrome available
before_install:
  - npm install -g @lhci/cli@0.3.x # install LHCI
script:
  - echo BUILD PASS
  - lhci autorun --assert.preset=lighthouse:recommended # run Lighthouse CI on your static site and assert the recommended preset
