#!/usr/bin/env python3
"""Rasterize Natural Earth 110m land polygons into a 1-bit equirectangular bitmap.

Usage: python3 scripts/bake-land.py [land.geojson]

Source: https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
Output: src/app/components/ascii-globe/land-data.ts (base64, row-major, MSB first)
"""
import base64
import json
import sys
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
WIDTH, HEIGHT = 360, 180  # 1 degree per cell
OUT = Path(__file__).resolve().parent.parent / "src/app/components/ascii-globe/land-data.ts"


def project(ring):
    return [((lon + 180) / 360 * WIDTH, (90 - lat) / 180 * HEIGHT) for lon, lat in ring]


def main():
    if len(sys.argv) > 1:
        data = json.loads(Path(sys.argv[1]).read_text())
    else:
        data = json.loads(urllib.request.urlopen(URL, timeout=60).read())

    img = Image.new("1", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(img)
    for feature in data["features"]:
        geom = feature["geometry"]
        polys = [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]
        for poly in polys:
            draw.polygon(project(poly[0]), fill=1)
            for hole in poly[1:]:
                draw.polygon(project(hole), fill=0)

    packed = base64.b64encode(img.tobytes()).decode()
    OUT.write_text(
        "// Generated by scripts/bake-land.py from Natural Earth 110m land. Do not edit.\n"
        f"export const LAND_WIDTH = {WIDTH};\n"
        f"export const LAND_HEIGHT = {HEIGHT};\n"
        "// 1 bit per cell, row-major from the north pole, column 0 = 180°W, MSB first, rows byte-aligned.\n"
        f"export const LAND_BITS = '{packed}';\n"
    )
    land = sum(1 for px in img.getdata() if px)
    print(f"wrote {OUT} ({len(packed)} chars, {land}/{WIDTH * HEIGHT} land cells)")


main()
