#!/usr/bin/env python3
"""Rasterize Natural Earth ice and desert polygons into a 2-bit-per-cell terrain bitmap.

Requires Pillow (pip install pillow).
Usage: python3 scripts/bake-terrain.py [glaciated.geojson regions.geojson]

Sources, pinned to the same natural-earth-vector commit as bake-land.py so re-running
produces the same output:
  ne_50m_glaciated_areas.geojson          -> ice
  ne_50m_geography_regions_polys.geojson  -> deserts (FEATURECLA "Desert")
Output: src/app/components/ascii-globe/terrain-data.ts

Each cell holds 0 = vegetation, 1 = desert, 2 = ice. The globe only looks a cell up where the
land bitmap (land-data.ts) says land, so ocean is not stored here. Ice wins over desert.
"""
import base64
import json
import sys
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw

SOURCE_COMMIT = "ca96624a56bd078437bca8184e78163e5039ad19"
BASE = f"https://raw.githubusercontent.com/nvkelso/natural-earth-vector/{SOURCE_COMMIT}/geojson"
WIDTH, HEIGHT = 360, 180  # 1 degree per cell, same grid as land-data.ts
OUT = Path(__file__).resolve().parent.parent / "src/app/components/ascii-globe/terrain-data.ts"

# Natural Earth tags these "Desert" but they are not arid: Caatinga is Brazilian scrubland
# and the Punjab is irrigated farmland.
NOT_DESERT = {"CAATINGAS", "PUNJAB"}


def load(arg, name):
    if arg:
        return json.loads(Path(arg).read_text())
    return json.loads(urllib.request.urlopen(f"{BASE}/{name}.geojson", timeout=120).read())


def project(ring):
    return [((lon + 180) / 360 * WIDTH, (90 - lat) / 180 * HEIGHT) for lon, lat in ring]


def paint(draw, features):
    for feature in features:
        geom = feature["geometry"]
        polys = [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]
        for poly in polys:
            draw.polygon(project(poly[0]), fill=1)
            for hole in poly[1:]:
                draw.polygon(project(hole), fill=0)


def layer(features):
    img = Image.new("1", (WIDTH, HEIGHT), 0)
    paint(ImageDraw.Draw(img), features)
    return img


def main():
    ice_data = load(sys.argv[1] if len(sys.argv) > 2 else None, "ne_50m_glaciated_areas")
    region_data = load(sys.argv[2] if len(sys.argv) > 2 else None, "ne_50m_geography_regions_polys")
    deserts = [
        f for f in region_data["features"]
        if f["properties"]["FEATURECLA"] == "Desert" and f["properties"]["NAME"].upper() not in NOT_DESERT
    ]
    ice = list(layer(ice_data["features"]).getdata())
    desert = list(layer(deserts).getdata())
    cells = [2 if i else 1 if d else 0 for i, d in zip(ice, desert)]

    # 2 bits per cell, row-major from the north pole, MSB first, rows byte-aligned (90 bytes).
    row_bytes = (WIDTH + 3) // 4
    packed = bytearray(row_bytes * HEIGHT)
    for y in range(HEIGHT):
        for x in range(WIDTH):
            packed[y * row_bytes + (x >> 2)] |= cells[y * WIDTH + x] << (6 - 2 * (x & 3))
    b64 = base64.b64encode(bytes(packed)).decode()
    OUT.write_text(
        "// Generated by scripts/bake-terrain.py from Natural Earth 50m glaciated areas and geography regions. Do not edit.\n"
        f"export const TERRAIN_WIDTH = {WIDTH};\n"
        f"export const TERRAIN_HEIGHT = {HEIGHT};\n"
        "// 2 bits per cell (0 = vegetation, 1 = desert, 2 = ice), row-major from the north pole,\n"
        "// column 0 = 180°W, MSB first, rows byte-aligned. Only meaningful where the land bitmap says land.\n"
        f"export const TERRAIN_BITS = '{b64}';\n"
    )
    print(f"wrote {OUT} ({len(b64)} chars, {cells.count(1)} desert, {cells.count(2)} ice cells)")


if __name__ == "__main__":
    main()
